# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/MDMx/ARTY2/ARTY2.cache/wt [current_project]
set_property parent.project_path C:/Users/MDMx/ARTY2/ARTY2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/MDMx/ARTY2/ARTY2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/MDMx/ARTY2/ARTY2.srcs/sources_1/new/swing_counter.v
  C:/Users/MDMx/ARTY2/ARTY2.srcs/sources_1/new/PWM_module.v
  C:/Users/MDMx/ARTY2/ARTY2.srcs/sources_1/imports/Arty_sw_btn_led/sw_btn_led.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/MDMx/ARTY2/ARTY2.srcs/constrs_1/new/Pin1.xdc
set_property used_in_implementation false [get_files C:/Users/MDMx/ARTY2/ARTY2.srcs/constrs_1/new/Pin1.xdc]


synth_design -top sw_btn_led -part xc7a35ticsg324-1L


write_checkpoint -force -noxdef sw_btn_led.dcp

catch { report_utilization -file sw_btn_led_utilization_synth.rpt -pb sw_btn_led_utilization_synth.pb }
