set_property PACKAGE_PIN H5 [get_ports {led[3]}]
set_property PACKAGE_PIN J5 [get_ports {led[2]}]
set_property PACKAGE_PIN T9 [get_ports {led[1]}]
set_property PACKAGE_PIN T10 [get_ports {led[0]}]
set_property PACKAGE_PIN D9 [get_ports {btn[3]}]
set_property PACKAGE_PIN C9 [get_ports {btn[2]}]
set_property PACKAGE_PIN B9 [get_ports {btn[1]}]
set_property PACKAGE_PIN B8 [get_ports {btn[0]}]
set_property PACKAGE_PIN A8 [get_ports {sw[3]}]
set_property PACKAGE_PIN C11 [get_ports {sw[2]}]
set_property PACKAGE_PIN C10 [get_ports {sw[1]}]
set_property PACKAGE_PIN A10 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {btn[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {btn[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {btn[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {btn[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[0]}]

set_property PACKAGE_PIN E3 [get_ports clk_100M]
set_property IOSTANDARD LVCMOS18 [get_ports clk_100M]

create_clock -period 10.000 -name clk_100M -waveform {0.000 5.000} [get_ports clk_100M]
